on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name : 📂 Install dependencies
      uses : actions/setup-node@v2
      with : 
          node-version : '14'

    - name: 📂 Install npm dependencies
      run:  npm install
        
        
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp-delicegulo.alwaysdata.net
        username: delicegulo
        password: ${{ secrets.ftp_password }}
        protocol: ftps
        port : 21
        server -dir: /www/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/bootstrap/scss/**
          **/node_modules/bootstrap/js/**
          **/node_modules/bootstrap-icons/icons/**
        
